/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colorobserver;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author toshi
 */
public class VentanaColor extends javax.swing.JFrame implements Observer{
private ClaseObservador observador;
    /**
     * Creates new form VentanaColor
     */
    public VentanaColor() {
        initComponents();
    }
public VentanaColor(ClaseObservador observador){
    initComponents();
    this.observador=observador;
    setTitle("Usuario S");
    setLocationRelativeTo(null);
    setLocation(this.getX()+this.getWidth(), this.getY());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RadAmarillo = new javax.swing.JRadioButton();
        RadAzul = new javax.swing.JRadioButton();
        RadBlanco = new javax.swing.JRadioButton();
        RadNegro = new javax.swing.JRadioButton();
        RadRojo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un Color");

        buttonGroup1.add(RadAmarillo);
        RadAmarillo.setText("Amarillo");
        RadAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadAmarilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadAzul);
        RadAzul.setText("Azul");
        RadAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadAzulActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadBlanco);
        RadBlanco.setText("Blanco");
        RadBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBlancoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadNegro);
        RadNegro.setText("Negro");
        RadNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadNegroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadRojo);
        RadRojo.setText("Rojo");
        RadRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadRojoActionPerformed(evt);
            }
        });

        jLabel2.setText("Color Seleccionado");

        lblColor.setToolTipText("");
        lblColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadRojo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(RadAzul)
                            .addComponent(RadAmarillo)
                            .addComponent(RadNegro)
                            .addComponent(RadBlanco))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadAmarillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadAzul)
                        .addGap(8, 8, 8)
                        .addComponent(RadBlanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadNegro))
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadRojo)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAmarilloActionPerformed
        // TODO add your handling code here:
       if(RadAmarillo.isSelected()){
           observador.setColor(Color.yellow);
       }
    }//GEN-LAST:event_RadAmarilloActionPerformed

    private void RadAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAzulActionPerformed
        // TODO add your handling code here:
        if(RadAzul.isSelected()){
           observador.setColor(Color.blue);
       }
    }//GEN-LAST:event_RadAzulActionPerformed

    private void RadBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBlancoActionPerformed
        // TODO add your handling code here:
        if(RadBlanco.isSelected()){
            observador.setColor(Color.white);
        }
    }//GEN-LAST:event_RadBlancoActionPerformed

    private void RadNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadNegroActionPerformed
        // TODO add your handling code here:
         if(RadNegro.isSelected()){
            observador.setColor(Color.black);
        }
    }//GEN-LAST:event_RadNegroActionPerformed

    private void RadRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadRojoActionPerformed
        // TODO add your handling code here:
        if(RadRojo.isSelected()){
            observador.setColor(Color.red);
        }
    }//GEN-LAST:event_RadRojoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadAmarillo;
    private javax.swing.JRadioButton RadAzul;
    private javax.swing.JRadioButton RadBlanco;
    private javax.swing.JRadioButton RadNegro;
    private javax.swing.JRadioButton RadRojo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblColor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        lblColor.setBackground(observador.getColor());
        switch(observador.getColores().indexOf(observador.getColor()))
        {
            case 0:RadAmarillo.setSelected(true);break;
            case 1:RadAzul.setSelected(true);break;
            case 2:RadBlanco.setSelected(true);break;
            case 3:RadNegro.setSelected(true);break;
            case 4:RadRojo.setSelected(true);break;
        }   
    }
    
    
}
